/**
 * QA / screenshot seed rows (scripts/seed-phase3a2-test-data.mjs). Hidden in lists and
 * removable via scripts/cleanup-demo-seed-data.mjs — never shown to production users.
 */

export const DEMO_DETAIL_MARKERS = [
  "phase3a2-seed",
  "Phase 3A-4 Step",
  "stage advance demo",
  "Hub Step 2 Demo",
  "Step 3 Advance Demo",
  "Design Empty Demo",
  "Survey Empty Demo",
  "Comments Empty Demo",
  "API Smoke Test",
  "via POST — will delete",
] as const;

export const DEMO_OFFICIAL_NAMES = [
  "Ravi Sharma — 5kW Rooftop",
  "Green Valley Apartments — 25kW",
  "Patel Industries — 50kW",
  "Hub Step 2 Demo",
  "Step 3 Advance Demo",
  "Design Empty Demo",
  "Survey Empty Demo",
  "Comments Empty Demo",
  "API Smoke Test",
] as const;

export const DEMO_LEAD_NAMES = ["Ravi Sharma", "Amit Verma"] as const;

export const DEMO_LEAD_CITIES: Record<(typeof DEMO_LEAD_NAMES)[number], string> = {
  "Ravi Sharma": "Udaipur",
  "Amit Verma": "Jaipur",
};

/** Phones generated by seed-phase3a2-test-data.mjs (98765* / 98766* + 5-digit stamp). */
export function isDemoSeedPhone(phone: unknown): boolean {
  const digits = String(phone ?? "").replace(/\D/g, "");
  return /^9876[56]\d{5}$/.test(digits);
}

export function isDemoSeedLead(row: Record<string, unknown>): boolean {
  const name = String(row.name ?? "").trim();
  const city = String(row.city ?? "").trim();
  if (isDemoSeedPhone(row.phone)) return true;
  if (!DEMO_LEAD_NAMES.includes(name as (typeof DEMO_LEAD_NAMES)[number])) return false;
  return city === DEMO_LEAD_CITIES[name as (typeof DEMO_LEAD_NAMES)[number]];
}

export function isDemoSeedProject(row: Record<string, unknown>, demoLeadIds?: Set<string>): boolean {
  const detail = String(row.detail ?? "");
  if (DEMO_DETAIL_MARKERS.some((m) => detail.includes(m))) return true;

  const name = String(row.official_name ?? row.customer_name ?? "");
  if (DEMO_OFFICIAL_NAMES.some((n) => name === n || name.startsWith(n))) return true;
  if (name === "Ravi Sharma" || name.startsWith("Ravi Sharma —")) return true;

  const code = String(row.project_code ?? "");
  if (/^SOL-\d{6}-00[123]$/.test(code)) return true;
  if (code === "SOL-HUB-S3") return true;

  const leadId = row.lead_id != null ? String(row.lead_id) : "";
  if (leadId && demoLeadIds?.has(leadId)) return true;

  return false;
}

export function filterOutDemoSeedLeads<T extends Record<string, unknown>>(rows: T[]): T[] {
  return rows.filter((row) => !isDemoSeedLead(row));
}

export function buildDemoSeedLeadIdSet(leads: Record<string, unknown>[]): Set<string> {
  const ids = new Set<string>();
  for (const row of leads) {
    if (isDemoSeedLead(row)) ids.add(String(row.id));
  }
  return ids;
}

export function filterOutDemoSeedProjects<T extends Record<string, unknown>>(
  rows: T[],
  demoLeadIds?: Set<string>
): T[] {
  const ids = demoLeadIds ?? new Set<string>();
  return rows.filter((row) => !isDemoSeedProject(row, ids));
}
